#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sys /sys

modprobe soundcore
modprobe snd
modprobe snd_page_alloc
modprobe snd_timer
modprobe snd_pcm
modprobe snd_seq_device
modprobe snd_seq
modprobe snd_hwdep
# AC'97
modprobe ac97_bus
modprobe snd-ac97-codec
modprobe snd-intel8x0
