#!/bin/sh
#
# http://www.maxwit.com
# http://maxwit.googlecode.com
#
# Authors:
#     Conke Hu    <conke@maxwit.com>
#     Tiger Yu    <tiger@maxwit.com>
#     Fleya Hou   <fleya@maxwit.com>
#


# UTILS_TOP="${MW_TOP_DIR}/host"

QEMU_HOST_IP="10.0.0.1"
QEMU_MACH_IP="10.0.0.2"


build_utils()
{
	mkdir -vp ${UTILS_ROOT}/usr/bin
	mkdir -vp ${UTILS_ROOT}/usr/lib
	mkdir -vp ${UTILS_ROOT}/usr/share/man/man1
	echo

	for pkg in \
		${MWP_GETTEXT} \
		${MWP_M4} \
		${MWP_LIBTOOL} \
		${MWP_FLEX} \
		${MWP_BISON} \
		${MWP_SED} \
		${MWP_GAWK} \
		${MWP_TEXINFO} \
		${MWP_GMP} \
		${MWP_MPFR} \
		${MWP_MPC} \
		${MWP_AUTOCONF} \
		${MWP_AUTOMAKE} \
		;
	do
		build_package ${pkg} host
	done

#	sed -i "s:\(.*my.*ENV.*\)libtoolize:\1${UTILS_ROOT}/bin/libtoolize:" ${UTILS_PREFIX}/bin/autoreconf || exit 1
# ${MWP_PKG_CONFIG} \
# ${MWP_PATCH} \
}


qemu_setup()
{
	sudo touch /etc/qemu-ifup && \
	sudo chmod 777 /etc/qemu-ifup && \
	sudo touch /etc/qemu-ifdown && \
	sudo chmod 777 /etc/qemu-ifdown

	echo '#!/bin/sh' > /etc/qemu-ifup
	echo "/sbin/ifconfig \$1 ${QEMU_HOST_IP}" >> /etc/qemu-ifup
#	chmod a+x /etc/qemu-ifup

	echo '#!/bin/sh' > /etc/qemu-ifdown
	echo "/sbin/ifconfig \$1 down" >> /etc/qemu-ifdown
#	chmod a+x /etc/qemu-ifdown
}

