#!/bin/sh
#
# http://www.maxwit.com
# http://maxwit.googlecode.com
#
# Authors:
#     Conke Hu    <conke@maxwit.com>
#     Tiger Yu    <tiger@maxwit.com>
#     Fleya Hou   <fleya@maxwit.com>
#


build_toolchain()
{
	check_pkgs ${MWP_KERNEL}
	unpack_to ${MWP_KERNEL} target
	if [ ! -f .__lablin_kernel_header_installed ]; then
		make ARCH=${TARGET_ARCH} INSTALL_HDR_PATH=${TOOLCHAIN_PATH}/usr headers_install || exit 1
		touch .__lablin_kernel_header_installed
	fi

	export MWP_BINUTILS MWP_GCC MWP_GLIBC

	for pkg in \
		${MWP_BINUTILS} \
		${MWP_GCC} \
		${MWP_GLIBC} \
		;
	do
		build_package ${pkg} toolchain
	done

	if [ ! -f ${BUILD_PATH}/toolchain/${MWP_GCC}/.lablin_gccp2_built ]; then
		mkdir -p ${BUILD_PATH}/toolchain/${MWP_GCC}-build2 && \
		cd ${BUILD_PATH}/toolchain/${MWP_GCC}-build2 && \
		${MW_TOP_DIR}/toolchain/${MWP_GCC}/build_pass2.sh || exit 1
		touch ../${MWP_GCC}/.lablin_gccp2_built

		# fixme
		cd ${TOOLCHAIN_PATH}/usr/bin
		for file in `ls ${TARGET_PLAT}-*`
		do
			ln -vs ${file} ${TARGET_ARCH}-linux${file##${TARGET_PLAT}}
		done
	
		ln -vs ${TARGET_PLAT}-gcc ${TARGET_PLAT}-cc
	
		echo -n "Archive GNU Toolchain ..." # rootfs
		cd ${MAXWIT_TOP}
		dn=`basename ${TOOLCHAIN_PATH}`
		tar cf ${dn}.tar ${dn}
		echo
	fi
}
